In [18]:
import numpy as np
import pandas as pd

# Assignment 1: Series Basics
 

* Convert `oil_array` into a Pandas Series, called `oil_series`. Give it a name!
* Return the name, dtype, size, and index of `oil_series`.

Take the mean of the values array. 

Then, convert the series to integer datatype and recalculate the mean.

In [19]:
# create a DataFrame from the oil file, drop missing values
oil = pd.read_csv("oil.csv").dropna()

In [20]:
oil

            date  dcoilwtico
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
5     2013-01-08       93.21
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1175 rows x 2 columns]

In [21]:
oil_array = np.array(oil["dcoilwtico"].iloc[1000:1100])

In [22]:
oil_array

array([52.22, 51.44, 51.98, 52.01, 52.82, 54.01, 53.8 , 53.75, 52.36,
       53.26, 53.77, 53.98, 51.95, 50.82, 52.19, 53.01, 52.36, 52.45,
       51.12, 51.39, 52.33, 52.77, 52.38, 52.14, 53.24, 53.18, 52.63,
       52.75, 53.9 , 53.55, 53.81, 53.01, 52.19, 52.37, 52.99, 53.84,
       52.96, 53.21, 53.11, 53.41, 53.41, 54.02, 53.61, 54.48, 53.99,
       54.04, 54.  , 53.82, 52.63, 53.33, 53.19, 52.68, 49.83, 48.75,
       48.05, 47.95, 47.24, 48.34, 48.3 , 48.34, 47.79, 47.02, 47.29,
       47.  , 47.3 , 47.02, 48.36, 49.47, 50.3 , 50.54, 50.25, 50.99,
       51.14, 51.69, 52.25, 53.06, 53.38, 53.12, 53.19, 52.62, 52.46,
       50.49, 50.26, 49.64, 48.9 , 49.22, 49.22, 48.96, 49.31, 48.83,
       47.65, 47.79, 45.55, 46.23, 46.46, 45.84, 47.28, 47.81, 47.83,
       48.86])

In [23]:
oil_series =pd.Series(oil_array,name="oil price")

In [24]:
oil_series

0     52.22
1     51.44
2     51.98
3     52.01
4     52.82
      ...
95    45.84
96    47.28
97    47.81
98    47.83
99    48.86
Name: oil price, Length: 100, dtype: float64

In [25]:
print("name of sereis --",oil_series.name)
print("datatype of series --",oil_series.dtype)
print("size od series--",oil_series.size)
print("index of series--",oil_series.index)

name of sereis -- oil price
datatype of series -- float64
size od series-- 100
index of series-- RangeIndex(start=0, stop=100, step=1)

In [26]:
print("mean --",oil_series.values.mean())

mean -- 51.128299999999996

In [27]:
oil_series.dtype

dtype('float64')

In [28]:
integer_oil =oil_series.astype('int').mean()

In [29]:
integer_oil

50.66

##  Assignment 2:  Accessing Series Data

* Set the date series, which has been created below, to be the index of the oil price series created in assignment 1.


* Then, take the mean of the first 10 and last 10 prices of the series.


* Finally, grab all oil prices from January 1st, 2017 - January 7th, 2017 (inclusive) and set the index to the default integer index.

In [30]:
oil_series

0     52.22
1     51.44
2     51.98
3     52.01
4     52.82
      ...
95    45.84
96    47.28
97    47.81
98    47.83
99    48.86
Name: oil price, Length: 100, dtype: float64

In [31]:
date_series=pd.Series(oil['date'].iloc[1000:1100])

In [32]:
date_series

1035    2016-12-20
1036    2016-12-21
1037    2016-12-22
1038    2016-12-23
1040    2016-12-27
           ...
1135    2017-05-09
1136    2017-05-10
1137    2017-05-11
1138    2017-05-12
1139    2017-05-15
Name: date, Length: 100, dtype: object

In [33]:
#Set the date series, which has been created , to be the index of the 
#oil price series created in assignment 1
oil_series.index=date_series

In [34]:
oil_series

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
              ...
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: oil price, Length: 100, dtype: float64

In [35]:
oil_series.index

Index(['2016-12-20', '2016-12-21', '2016-12-22', '2016-12-23', '2016-12-27',
       '2016-12-28', '2016-12-29', '2016-12-30', '2017-01-03', '2017-01-04',
       '2017-01-05', '2017-01-06', '2017-01-09', '2017-01-10', '2017-01-11',
       '2017-01-12', '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25', '2017-01-26',
       '2017-01-27', '2017-01-30', '2017-01-31', '2017-02-01', '2017-02-02',
       '2017-02-03', '2017-02-06', '2017-02-07', '2017-02-08', '2017-02-09',
       '2017-02-10', '2017-02-13', '2017-02-14', '2017-02-15', '2017-02-16',
       '2017-02-17', '2017-02-21', '2017-02-22', '2017-02-23', '2017-02-24',
       '2017-02-27', '2017-02-28', '2017-03-01', '2017-03-02', '2017-03-03',
       '2017-03-06', '2017-03-07', '2017-03-08', '2017-03-09', '2017-03-10',
       '2017-03-13', '2017-03-14', '2017-03-15', '2017-03-16', '2017-03-17',
       '2017-03-20', '2017-03-21', '2017-03-22', '2017-03-23', '2017-03-24',
       '2017-03-27', '2017-03-28', '2017-03-29', '2017-03-30', '2017-03-31',
       '2017-04-03', '2017-04-04', '2017-04-05', '2017-04-06', '2017-04-07',
       '2017-04-10', '2017-04-11', '2017-04-12', '2017-04-13', '2017-04-17',
       '2017-04-18', '2017-04-19', '2017-04-20', '2017-04-21', '2017-04-24',
       '2017-04-25', '2017-04-26', '2017-04-27', '2017-04-28', '2017-05-01',
       '2017-05-02', '2017-05-03', '2017-05-04', '2017-05-05', '2017-05-08',
       '2017-05-09', '2017-05-10', '2017-05-11', '2017-05-12', '2017-05-15'],
      dtype='object', name='date')

In [36]:
#first 10 element in oil series
oil_series.iloc[:10]

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
2016-12-28    54.01
2016-12-29    53.80
2016-12-30    53.75
2017-01-03    52.36
2017-01-04    53.26
Name: oil price, dtype: float64

In [37]:
#first 10 element mean
oil_series.iloc[:10].mean()

52.765

In [38]:
#last ten element in oil series
oil_series.iloc[-10:]

date
2017-05-02    47.65
2017-05-03    47.79
2017-05-04    45.55
2017-05-05    46.23
2017-05-08    46.46
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: oil price, dtype: float64

In [39]:
#last ten element mean
oil_series.iloc[-10:].mean()

47.13

In [40]:
#grab all oil prices from January 1st, 2017 - January 7th, 2017 (inclusive)
#and set the index to the default integer index.

oil_series.loc['2017-01-01':'2017-01-07'].reset_index(drop=True)

0    52.36
1    53.26
2    53.77
3    53.98
Name: oil price, dtype: float64

## Assignment 3: Sorting and Filtering Series

* First, get the 10 lowest prices from the data. 
* Sort the 10 lowest prices by date, starting with the most recent and ending with the oldest price.

* Finally, use the list of provided dates. Select only rows with these dates that had a price of less than 50 dollars per barrel.

In [41]:
oil

            date  dcoilwtico
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
5     2013-01-08       93.21
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1175 rows x 2 columns]

In [42]:
oil_price =pd.Series(oil['dcoilwtico'])

In [43]:
lowest_10 = oil_price.sort_values()
lowest_10[0:10]

812    26.19
796    26.68
811    27.54
810    27.96
795    28.47
815    29.05
813    29.32
793    29.45
800    29.54
797    29.55
Name: dcoilwtico, dtype: float64

In [44]:
oil_series

date
2016-12-20    52.22
2016-12-21    51.44
2016-12-22    51.98
2016-12-23    52.01
2016-12-27    52.82
              ...
2017-05-09    45.84
2017-05-10    47.28
2017-05-11    47.81
2017-05-12    47.83
2017-05-15    48.86
Name: oil price, Length: 100, dtype: float64