# <center>Pandas Dataframe Tasks</center>

In [1]:
import pandas as pd
import numpy as np

##  Assignment 1: DataFrame Basics

Hi there!

Can you read in the transactions dataset and report on:

* The number of rows and columns
* The names of the columns
* The datatypes of each column

In [2]:
transaction_df =pd.read_csv("transactions.csv")

In [3]:
transaction_df

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [4]:
print("The number of rows and columns --",transaction_df.shape)
print("The name of columns --",transaction_df.columns)
print("The datatype of columns --",transaction_df.dtypes)

The number of rows and columns -- (83488, 3)
The name of columns -- Index(['date', 'store_nbr', 'transactions'], dtype='object')
The datatype of columns -- date            object
store_nbr        int64
transactions     int64
dtype: object

In [5]:
#to get the row count

row_count = transaction_df.index.max() + 1

row_count

83488

## Assignment 2: Exploring DataFrames

Hello!

* Can you quickly inspect the first 5 rows of the transactions data? 

* Then, dive a bit more deeply into the data and check if there are any missing values.
* What about the number of unique dates? I want to make sure we didn’t leave any out.
* Finally, can you report the mean, median, min and max of “transactions”?  I want to check for any anomalies in our data.

In [6]:
#first 5 rows of transaction data
transaction_df.head(5)

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [7]:
#isna() and sum() is to find the missing data
transaction_df.isna().sum()

date            0
store_nbr       0
transactions    0
dtype: int64

In [8]:
#info() is used to find the missing count by comparing with range index
#non-null count
transaction_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  object
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), object(1)
memory usage: 1.9+ MB

In [9]:
#no of unique dates
transaction_df["date"].nunique()

1682

In [10]:
transaction_df.describe()

          store_nbr  transactions
count  83488.000000  83488.000000
mean      26.939237   1694.602158
std       15.608204    963.286644
min        1.000000      5.000000
25%       13.000000   1046.000000
50%       27.000000   1393.000000
75%       40.000000   2079.000000
max       54.000000   8359.000000

## Exercise 3 - Accessing DataFrames

Hi, starting to dive deeper into this data.

I noticed that the first row is the only one from 2013-01-01.

* Can you get me a copy of the DataFrame that excludes that row, and only includes “store_nbr” and “transactions”?
* Also, can you report the number of unique store numbers?
* Finally, return the total number of transactions in millions

In [11]:
transaction_df.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

In [12]:
#copy of dataframe that exclude first row
transaction_df.loc[1:,"store_nbr":"transcations"]

       store_nbr  transactions
1              1          2111
2              2          2358
3              3          3487
4              4          1922
5              5          1903
...          ...           ...
83483         50          2804
83484         51          1573
83485         52          2255
83486         53           932
83487         54           802

[83487 rows x 2 columns]

In [13]:
# report the number of unique store numbers
transaction_df["store_nbr"].nunique()

54

In [14]:
#return the total number of transaction in million
transaction_df["transactions"].sum()/1000000

141.478945

##  Assignment 4: Dropping Data and Duplicates

Hi there!

Can you:

1. Drop the first row of data? We want it permanently removed. 
2. Drop the date column but not in place
3. Return a dataframe that only includes the last row for each of the stores.

In [15]:
transaction_df.drop(0,axis =0,inplace=True)

In [16]:
transaction_df

             date  store_nbr  transactions
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
5      2013-01-02          5          1903
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83487 rows x 3 columns]

In [17]:
#drop the date column but not inplace

transaction_df.drop("date",axis=1,inplace=False)

       store_nbr  transactions
1              1          2111
2              2          2358
3              3          3487
4              4          1922
5              5          1903
...          ...           ...
83483         50          2804
83484         51          1573
83485         52          2255
83486         53           932
83487         54           802

[83487 rows x 2 columns]

In [18]:
transaction_df

             date  store_nbr  transactions
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
5      2013-01-02          5          1903
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83487 rows x 3 columns]

In [19]:
# drop duplicate rows subsetting by store number. keep last entry for each store

transaction_df.drop_duplicates(subset="store_nbr",keep="last").head()

             date  store_nbr  transactions
83434  2017-08-15          1          1693
83435  2017-08-15          2          1737
83436  2017-08-15          3          2956
83437  2017-08-15          4          1283
83438  2017-08-15          5          1310

In [20]:
transaction_df

             date  store_nbr  transactions
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
5      2013-01-02          5          1903
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83487 rows x 3 columns]

## Assignment 5: Missing Data

Hello, 

Can you tell if any dates or prices are missing in the oil dataset?

Then compare the mean of the oil series when filling in with mean vs. filling in with 0.

Thanks!

In [27]:
oil_df =pd.read_csv("oil.csv")

In [28]:
oil_df

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [29]:
oil_df.isna().sum()

date           0
dcoilwtico    43
dtype: int64

In [30]:
oil_df

            date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1218 rows x 2 columns]

In [31]:
#calculate mean of oil series by filling null value with 0

oil_df["dcoilwtico"].fillna(0).mean()

65.32379310344828

In [33]:
#calculate mean of oil series by filling null value with mean

oil_df["dcoilwtico"].fillna(oil_df["dcoilwtico"].mean()).mean()

67.71436595744682

## Assignment 6: Filtering DataFrames

I need some quick research on store 25:

* First, calculate the percentage of times ALL stores had more than 2000 transactions
* Then, calculate the percentage of times store 25 had more than 2000 transactions, and calculate the sum of transactions on these days
* Finally, sum the transactions for stores 25 and 3, that occurred in May or June, and had less than 2000 transactions

In [34]:
transaction_df

             date  store_nbr  transactions
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
5      2013-01-02          5          1903
...           ...        ...           ...
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83487 rows x 3 columns]

In [44]:
#calculate the percentage of times all stores had more than 2000 transactions

(transaction_df["transactions"] >2000).mean()

0.266808006036868

In [51]:
trans25 =  transaction_df[(transaction_df["transactions"]>2000) & (transaction_df["store_nbr"] ==25)]
trans25.head(5)

            date  store_nbr  transactions
1770  2013-02-09         25          3091
1816  2013-02-10         25          3331
1862  2013-02-11         25          2763
2736  2013-03-02         25          2014
3978  2013-03-29         25          2442