# <center>Accessing and Dropping Data</center>

In [1]:
import pandas as pd
import numpy as np

In [4]:
retail_df =pd.read_csv("retail_2016_2017.csv")

In [5]:
retail_df

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [6]:
#accessing column
retail_df["family"]

0                          AUTOMOTIVE
1                           BABY CARE
2                              BEAUTY
3                           BEVERAGES
4                               BOOKS
                      ...
1054939                       POULTRY
1054940                PREPARED FOODS
1054941                       PRODUCE
1054942    SCHOOL AND OFFICE SUPPLIES
1054943                       SEAFOOD
Name: family, Length: 1054944, dtype: object

In [8]:
retail_df["family"].unique()

array(['AUTOMOTIVE', 'BABY CARE', 'BEAUTY', 'BEVERAGES', 'BOOKS',
       'BREAD/BAKERY', 'CELEBRATION', 'CLEANING', 'DAIRY', 'DELI', 'EGGS',
       'FROZEN FOODS', 'GROCERY I', 'GROCERY II', 'HARDWARE',
       'HOME AND KITCHEN I', 'HOME AND KITCHEN II', 'HOME APPLIANCES',
       'HOME CARE', 'LADIESWEAR', 'LAWN AND GARDEN', 'LINGERIE',
       'LIQUOR,WINE,BEER', 'MAGAZINES', 'MEATS', 'PERSONAL CARE',
       'PET SUPPLIES', 'PLAYERS AND ELECTRONICS', 'POULTRY',
       'PREPARED FOODS', 'PRODUCE', 'SCHOOL AND OFFICE SUPPLIES',
       'SEAFOOD'], dtype=object)

In [9]:
retail_df["sales"].sum().round()

482871591.0

In [10]:
#accessing multiple column

retail_df[["sales","family"]]

            sales                      family
0           0.000                  AUTOMOTIVE
1           0.000                   BABY CARE
2           0.000                      BEAUTY
3           0.000                   BEVERAGES
4           0.000                       BOOKS
...           ...                         ...
1054939   438.133                     POULTRY
1054940   154.553              PREPARED FOODS
1054941  2419.729                     PRODUCE
1054942   121.000  SCHOOL AND OFFICE SUPPLIES
1054943    16.000                     SEAFOOD

[1054944 rows x 2 columns]

In [18]:
retail_df.columns

Index(['id', 'date', 'store_nbr', 'family', 'sales', 'onpromotion'], dtype='object')

In [21]:
#using .loc() and .iloc() access rows and columns

retail_df.iloc[:,2:5]

         store_nbr                      family     sales
0                1                  AUTOMOTIVE     0.000
1                1                   BABY CARE     0.000
2                1                      BEAUTY     0.000
3                1                   BEVERAGES     0.000
4                1                       BOOKS     0.000
...            ...                         ...       ...
1054939          9                     POULTRY   438.133
1054940          9              PREPARED FOODS   154.553
1054941          9                     PRODUCE  2419.729
1054942          9  SCHOOL AND OFFICE SUPPLIES   121.000
1054943          9                     SEAFOOD    16.000

[1054944 rows x 3 columns]

In [22]:
retail_df.loc[:10,"store_nbr":"sales"]

    store_nbr        family  sales
0           1    AUTOMOTIVE    0.0
1           1     BABY CARE    0.0
2           1        BEAUTY    0.0
3           1     BEVERAGES    0.0
4           1         BOOKS    0.0
5           1  BREAD/BAKERY    0.0
6           1   CELEBRATION    0.0
7           1      CLEANING    0.0
8           1         DAIRY    0.0
9           1          DELI    0.0
10          1          EGGS    0.0

In [23]:
retail_df.loc[:10,["store_nbr","sales"]]

    store_nbr  sales
0           1    0.0
1           1    0.0
2           1    0.0
3           1    0.0
4           1    0.0
5           1    0.0
6           1    0.0
7           1    0.0
8           1    0.0
9           1    0.0
10          1    0.0