# <center>Modifying columns</center>

In [1]:
import pandas as pd
import numpy as np

In [2]:
product_df =pd.DataFrame({'product':["dairy","dairy","vegetables","fruits"],
                         'cost':[3,5,69,10]})

In [3]:
#renaming columns

product_df

      product  cost
0       dairy     3
1       dairy     5
2  vegetables    69
3      fruits    10

In [4]:
product_df.columns =["Product_name","Price"]

In [5]:
product_df

  Product_name  Price
0        dairy      3
1        dairy      5
2   vegetables     69
3       fruits     10

In [6]:
product_df.columns = [ x.upper() for x in product_df.columns]

In [7]:
product_df

  PRODUCT_NAME  PRICE
0        dairy      3
1        dairy      5
2   vegetables     69
3       fruits     10

In [13]:
#using .rename() method to rename the columns

product_df.rename(columns ={'PRODUCT_NAME':'Product_list','PRICE':'cost_of_product'})

  Product_list  cost_of_product
0        dairy                3
1        dairy                5
2   vegetables               69
3       fruits               10

In [15]:
#reordering columns

product_df.reindex(labels=['PRICE','PRODUCT_NAME'],axis=1)

   PRICE PRODUCT_NAME
0      3        dairy
1      5        dairy
2     69   vegetables
3     10       fruits

In [16]:
#arithmetic and boolean column creation
#by using series operation

retail_df =pd.read_csv("retail_2016_2017.csv")

In [17]:
retail_df

,id,date,store_nbr,family,sales,onpromotion
0,1945944,2016-01-01,1,AUTOMOTIVE,0.000,0
1,1945945,2016-01-01,1,BABY CARE,0.000,0
2,1945946,2016-01-01,1,BEAUTY,0.000,0
3,1945947,2016-01-01,1,BEVERAGES,0.000,0
4,1945948,2016-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
1054939,3000883,2017-08-15,9,POULTRY,438.133,0
1054940,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
1054941,3000885,2017-08-15,9,PRODUCE,2419.729,148
1054942,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
1054943,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [19]:
sample_df = retail_df.sample(20)

In [20]:
sample_df

,id,date,store_nbr,family,sales,onpromotion
334552,2280496,2016-07-06,45,SCHOOL AND OFFICE SUPPLIES,4.000,0
710113,2656057,2017-02-03,33,LADIESWEAR,0.000,0
601298,2547242,2016-12-03,30,BREAD/BAKERY,126.000,6
7430,1953374,2016-01-05,18,BREAD/BAKERY,722.000,0
450607,2396551,2016-09-09,51,PERSONAL CARE,429.000,4
599446,2545390,2016-12-02,29,BABY CARE,2.000,0
458431,2404375,2016-09-14,21,POULTRY,112.013,0
274524,2220468,2016-06-03,11,PRODUCE,1118.673,3
957144,2903088,2017-06-22,15,GROCERY I,2949.000,75
853479,2799423,2017-04-24,7,AUTOMOTIVE,4.000,0
851197,2797141,2017-04-23,41,POULTRY,277.891,0
37489,1983433,2016-01-22,11,BABY CARE,0.000,0
529559,2475503,2016-10-24,18,DAIRY,0.000,0
616322,2562266,2016-12-11,51,HARDWARE,0.000,0
314701,2260645,2016-06-25,39,GROCERY II,41.000,0
839640,2785584,2017-04-17,18,LINGERIE,10.000,0
899683,2845627,2017-05-20,52,BOOKS,0.000,0
38921,1984865,2016-01-22,50,HARDWARE,3.000,0
970507,2916451,2017-06-29,4,EGGS,99.000,0
48767,1994711,2016-01-28,27,PET SUPPLIES,6.000,0

In [24]:
sample_df["tax_amount"]=sample_df["sales"] * 0.05

In [25]:
sample_df

,id,date,store_nbr,family,sales,onpromotion,tax_amount
334552,2280496,2016-07-06,45,SCHOOL AND OFFICE SUPPLIES,4.000,0,0.20000
710113,2656057,2017-02-03,33,LADIESWEAR,0.000,0,0.00000
601298,2547242,2016-12-03,30,BREAD/BAKERY,126.000,6,6.30000
7430,1953374,2016-01-05,18,BREAD/BAKERY,722.000,0,36.10000
450607,2396551,2016-09-09,51,PERSONAL CARE,429.000,4,21.45000
599446,2545390,2016-12-02,29,BABY CARE,2.000,0,0.10000
458431,2404375,2016-09-14,21,POULTRY,112.013,0,5.60065
274524,2220468,2016-06-03,11,PRODUCE,1118.673,3,55.93365
957144,2903088,2017-06-22,15,GROCERY I,2949.000,75,147.45000
853479,2799423,2017-04-24,7,AUTOMOTIVE,4.000,0,0.20000
851197,2797141,2017-04-23,41,POULTRY,277.891,0,13.89455
37489,1983433,2016-01-22,11,BABY CARE,0.000,0,0.00000
529559,2475503,2016-10-24,18,DAIRY,0.000,0,0.00000
616322,2562266,2016-12-11,51,HARDWARE,0.000,0,0.00000
314701,2260645,2016-06-25,39,GROCERY II,41.000,0,2.05000
839640,2785584,2017-04-17,18,LINGERIE,10.000,0,0.50000
899683,2845627,2017-05-20,52,BOOKS,0.000,0,0.00000
38921,1984865,2016-01-22,50,HARDWARE,3.000,0,0.15000
970507,2916451,2017-06-29,4,EGGS,99.000,0,4.95000
48767,1994711,2016-01-28,27,PET SUPPLIES,6.000,0,0.30000

In [26]:
sample_df["total"] = sample_df["sales"] + sample_df["tax_amount"]

In [27]:
sample_df

,id,date,store_nbr,family,sales,onpromotion,tax_amount,total
334552,2280496,2016-07-06,45,SCHOOL AND OFFICE SUPPLIES,4.000,0,0.20000,4.20000
710113,2656057,2017-02-03,33,LADIESWEAR,0.000,0,0.00000,0.00000
601298,2547242,2016-12-03,30,BREAD/BAKERY,126.000,6,6.30000,132.30000
7430,1953374,2016-01-05,18,BREAD/BAKERY,722.000,0,36.10000,758.10000
450607,2396551,2016-09-09,51,PERSONAL CARE,429.000,4,21.45000,450.45000
599446,2545390,2016-12-02,29,BABY CARE,2.000,0,0.10000,2.10000
458431,2404375,2016-09-14,21,POULTRY,112.013,0,5.60065,117.61365
274524,2220468,2016-06-03,11,PRODUCE,1118.673,3,55.93365,1174.60665
957144,2903088,2017-06-22,15,GROCERY I,2949.000,75,147.45000,3096.45000
853479,2799423,2017-04-24,7,AUTOMOTIVE,4.000,0,0.20000,4.20000
851197,2797141,2017-04-23,41,POULTRY,277.891,0,13.89455,291.78555
37489,1983433,2016-01-22,11,BABY CARE,0.000,0,0.00000,0.00000
529559,2475503,2016-10-24,18,DAIRY,0.000,0,0.00000,0.00000
616322,2562266,2016-12-11,51,HARDWARE,0.000,0,0.00000,0.00000
314701,2260645,2016-06-25,39,GROCERY II,41.000,0,2.05000,43.05000
839640,2785584,2017-04-17,18,LINGERIE,10.000,0,0.50000,10.50000
899683,2845627,2017-05-20,52,BOOKS,0.000,0,0.00000,0.00000
38921,1984865,2016-01-22,50,HARDWARE,3.000,0,0.15000,3.15000
970507,2916451,2017-06-29,4,EGGS,99.000,0,4.95000,103.95000
48767,1994711,2016-01-28,27,PET SUPPLIES,6.000,0,0.30000,6.30000

In [23]:
sample_df["family"].value_counts()

BREAD/BAKERY                  2
BABY CARE                     2
POULTRY                       2
HARDWARE                      2
SCHOOL AND OFFICE SUPPLIES    1
LADIESWEAR                    1
PERSONAL CARE                 1
PRODUCE                       1
GROCERY I                     1
AUTOMOTIVE                    1
DAIRY                         1
GROCERY II                    1
LINGERIE                      1
BOOKS                         1
EGGS                          1
PET SUPPLIES                  1
Name: family, dtype: int64

In [28]:
#create boolean column by assigning the logical test

sample_df["tax_category"] = sample_df["family"] !="BABY CARE"

In [29]:
sample_df

,id,date,store_nbr,family,sales,onpromotion,tax_amount,total,tax_category
334552,2280496,2016-07-06,45,SCHOOL AND OFFICE SUPPLIES,4.000,0,0.20000,4.20000,True
710113,2656057,2017-02-03,33,LADIESWEAR,0.000,0,0.00000,0.00000,True
601298,2547242,2016-12-03,30,BREAD/BAKERY,126.000,6,6.30000,132.30000,True
7430,1953374,2016-01-05,18,BREAD/BAKERY,722.000,0,36.10000,758.10000,True
450607,2396551,2016-09-09,51,PERSONAL CARE,429.000,4,21.45000,450.45000,True
599446,2545390,2016-12-02,29,BABY CARE,2.000,0,0.10000,2.10000,False
458431,2404375,2016-09-14,21,POULTRY,112.013,0,5.60065,117.61365,True
274524,2220468,2016-06-03,11,PRODUCE,1118.673,3,55.93365,1174.60665,True
957144,2903088,2017-06-22,15,GROCERY I,2949.000,75,147.45000,3096.45000,True
853479,2799423,2017-04-24,7,AUTOMOTIVE,4.000,0,0.20000,4.20000,True
851197,2797141,2017-04-23,41,POULTRY,277.891,0,13.89455,291.78555,True
37489,1983433,2016-01-22,11,BABY CARE,0.000,0,0.00000,0.00000,False
529559,2475503,2016-10-24,18,DAIRY,0.000,0,0.00000,0.00000,True
616322,2562266,2016-12-11,51,HARDWARE,0.000,0,0.00000,0.00000,True
314701,2260645,2016-06-25,39,GROCERY II,41.000,0,2.05000,43.05000,True
839640,2785584,2017-04-17,18,LINGERIE,10.000,0,0.50000,10.50000,True
899683,2845627,2017-05-20,52,BOOKS,0.000,0,0.00000,0.00000,True
38921,1984865,2016-01-22,50,HARDWARE,3.000,0,0.15000,3.15000,True
970507,2916451,2017-06-29,4,EGGS,99.000,0,4.95000,103.95000,True
48767,1994711,2016-01-28,27,PET SUPPLIES,6.000,0,0.30000,6.30000,True