In [1]:
import pandas as pd
import numpy as np

# Assignment 1: Groupby

Can you return a table containing the top 10 stores by total transactions in the data?

Make sure they’re sorted from highest to lowest.

Thanks!

In [5]:
transaction =pd.read_csv("transactions.csv",parse_dates=["date"])

In [6]:
transaction

            date  store_nbr  transactions
0     2013-01-01         25           770
1     2013-01-02          1          2111
2     2013-01-02          2          2358
3     2013-01-02          3          3487
4     2013-01-02          4          1922
...          ...        ...           ...
83483 2017-08-15         50          2804
83484 2017-08-15         51          1573
83485 2017-08-15         52          2255
83486 2017-08-15         53           932
83487 2017-08-15         54           802

[83488 rows x 3 columns]

In [10]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  datetime64[ns]
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.9 MB

In [19]:
transaction.groupby("store_nbr")[["transactions"]].sum().sort_values("transactions",ascending=False).iloc[:10]

           transactions
store_nbr
44              7273093
47              6535810
45              6201115
46              5990113
3               5366350
48              5107785
8               4637971
49              4574103
50              4384444
11              3972488

## Assignment 2: Groupby Multiple Columns

Can you get me the total transactions by store and month? 

Sort the table from first month to last, then by highest transactions to lowest within each month.

In [24]:
transaction["month"]=transaction["date"].dt.month

In [25]:
transaction

            date  store_nbr  transactions  month
0     2013-01-01         25           770      1
1     2013-01-02          1          2111      1
2     2013-01-02          2          2358      1
3     2013-01-02          3          3487      1
4     2013-01-02          4          1922      1
...          ...        ...           ...    ...
83483 2017-08-15         50          2804      8
83484 2017-08-15         51          1573      8
83485 2017-08-15         52          2255      8
83486 2017-08-15         53           932      8
83487 2017-08-15         54           802      8

[83488 rows x 4 columns]

In [27]:
(transaction.groupby(["store_nbr","month"])[["transactions"]]
.sum().sort_values(["month","transactions"],ascending=[True,False]))

                 transactions
store_nbr month
44        1            628438
47        1            568824
45        1            538370
46        1            522763
3         1            463260
...                       ...
32        12            86167
21        12            84128
42        12            76741
29        12            76627
22        12            50650

[641 rows x 1 columns]