In [11]:
import pandas as pd
import numpy as np

# Assignment 1: Groupby

Can you return a table containing the top 10 stores by total transactions in the data?

Make sure they’re sorted from highest to lowest.

Thanks!

In [12]:
transaction =pd.read_csv("transactions.csv",parse_dates=["date"])

In [13]:
transaction

            date  store_nbr  transactions
0     2013-01-01         25           770
1     2013-01-02          1          2111
2     2013-01-02          2          2358
3     2013-01-02          3          3487
4     2013-01-02          4          1922
...          ...        ...           ...
83483 2017-08-15         50          2804
83484 2017-08-15         51          1573
83485 2017-08-15         52          2255
83486 2017-08-15         53           932
83487 2017-08-15         54           802

[83488 rows x 3 columns]

In [14]:
transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  datetime64[ns]
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: datetime64[ns](1), int64(2)
memory usage: 1.9 MB

In [15]:
transaction.groupby("store_nbr")[["transactions"]].sum().sort_values("transactions",ascending=False).iloc[:10]

           transactions
store_nbr
44              7273093
47              6535810
45              6201115
46              5990113
3               5366350
48              5107785
8               4637971
49              4574103
50              4384444
11              3972488

## Assignment 2: Groupby Multiple Columns

Can you get me the total transactions by store and month? 

Sort the table from first month to last, then by highest transactions to lowest within each month.

In [16]:
transaction["month"]=transaction["date"].dt.month

In [17]:
transaction

            date  store_nbr  transactions  month
0     2013-01-01         25           770      1
1     2013-01-02          1          2111      1
2     2013-01-02          2          2358      1
3     2013-01-02          3          3487      1
4     2013-01-02          4          1922      1
...          ...        ...           ...    ...
83483 2017-08-15         50          2804      8
83484 2017-08-15         51          1573      8
83485 2017-08-15         52          2255      8
83486 2017-08-15         53           932      8
83487 2017-08-15         54           802      8

[83488 rows x 4 columns]

In [18]:
(transaction.groupby(["store_nbr","month"])[["transactions"]]
.sum().sort_values(["month","transactions"],ascending=[True,False]))

                 transactions
store_nbr month
44        1            628438
47        1            568824
45        1            538370
46        1            522763
3         1            463260
...                       ...
32        12            86167
21        12            84128
42        12            76741
29        12            76627
22        12            50650

[641 rows x 1 columns]

## Assignment 3: Multi-Index DataFrames


Can you help me access rows and columns with multiple indices? I’ve been struggling with multi-index DataFrames.

Access:
* Grab Store 3, Month 1
* Then, select the column storing the mean of transactions

Fix:
* Drop the outer layer of the column Index
* Reset the row index so it is the default integer index

In [34]:
group =(transaction.groupby(["store_nbr","month"])
        .agg({"transactions":["sum","mean"]})
       .sort_values(by=["month",("transactions","sum")],ascending=[True,False]))

In [35]:
group

                transactions
                         sum         mean
store_nbr month
44        1           628438  4246.202703
47        1           568824  3843.405405
45        1           538370  3637.635135
46        1           522763  3532.182432
3         1           463260  3151.428571
...                      ...          ...
32        12           86167   718.058333
21        12           84128  1402.133333
42        12           76741  1279.016667
29        12           76627  1277.116667
22        12           50650   844.166667

[641 rows x 2 columns]

In [36]:
#grab store 3,month 1
group.loc[(3,1)]

transactions  sum     463260.000000
              mean      3151.428571
Name: (3, 1), dtype: float64

In [39]:
group.loc[:,[("transactions","mean")]]

                transactions
                        mean
store_nbr month
44        1      4246.202703
47        1      3843.405405
45        1      3637.635135
46        1      3532.182432
3         1      3151.428571
...                      ...
32        12      718.058333
21        12     1402.133333
42        12     1279.016667
29        12     1277.116667
22        12      844.166667

[641 rows x 1 columns]

In [40]:
#Drop the outer layer of the column Index
#Reset the row index so it is the default integer index
group.head()

                transactions
                         sum         mean
store_nbr month
44        1           628438  4246.202703
47        1           568824  3843.405405
45        1           538370  3637.635135
46        1           522763  3532.182432
3         1           463260  3151.428571

In [41]:
group.reset_index()

    store_nbr month transactions
                             sum         mean
0          44     1       628438  4246.202703
1          47     1       568824  3843.405405
2          45     1       538370  3637.635135
3          46     1       522763  3532.182432
4           3     1       463260  3151.428571
..        ...   ...          ...          ...
636        32    12        86167   718.058333
637        21    12        84128  1402.133333
638        42    12        76741  1279.016667
639        29    12        76627  1277.116667
640        22    12        50650   844.166667

[641 rows x 4 columns]

In [42]:
group.droplevel(0,axis=1)

                    sum         mean
store_nbr month
44        1      628438  4246.202703
47        1      568824  3843.405405
45        1      538370  3637.635135
46        1      522763  3532.182432
3         1      463260  3151.428571
...                 ...          ...
32        12      86167   718.058333
21        12      84128  1402.133333
42        12      76741  1279.016667
29        12      76627  1277.116667
22        12      50650   844.166667

[641 rows x 2 columns]

In [44]:
group.droplevel(0,axis=1).reset_index()

     store_nbr  month     sum         mean
0           44      1  628438  4246.202703
1           47      1  568824  3843.405405
2           45      1  538370  3637.635135
3           46      1  522763  3532.182432
4            3      1  463260  3151.428571
..         ...    ...     ...          ...
636         32     12   86167   718.058333
637         21     12   84128  1402.133333
638         42     12   76741  1279.016667
639         29     12   76627  1277.116667
640         22     12   50650   844.166667

[641 rows x 4 columns]